### PR TITLE
Closes #49. Adds basic api for fetching stuff. PUTting is not yet don…

### LINKED ISSUE #49: Create API for mobile

### PR DESCRIPTION
**Pull request by tperamaki**
…e, or deleting

### CODE REVIEW

**Comment by eemeli-futurice** [comment]
Should we prefer async/await over `Promise().then()` or other way? We are starting to have both patterns in the codebase.

**Review by eemeli-futurice — APPROVED** [review]
Btw, do we want to move GET method behind authorization at some point?

**Comment by tperamaki** [comment]
I thought it was already

**Comment by eemeli-futurice** [comment]
It is! 🥳

**Pull request merged**
